### PR TITLE
Config with correct brands package. Update readme with install steps.

### PR DESCRIPTION
**Pull request by beausmith**
⚠️ v2.0.0 is broken for me.

These are the changes I had to make to get it to work. 

Please take a careful look over the changes in `config.js` to make sure that this is the correct way to do this. I'm pretty sure it it… at least with these changes, v2.0.1 is now working on both iOS and Android.

#### Installation before this PR is merged to master…
Add the following to your `package.json` file and then run `npm install` or `yarn`:
```
"react-native-fontawesome-pro": "beausmith/react-native-fontawesome-pro#v2-fixes",
```

### CODE REVIEW

**Review by shyaniv7 — APPROVED** [review]

**Comment by shyaniv7** [comment]
thanks for that! I copied those changes from another project I worked on and forgot about the brands package.

**Comment by shyaniv7** [comment]
Deprecated 2.0.0 and published 2.0.1 👍

**Comment by beausmith** [comment]
Sweet @shyaniv7. Does it all work for you?

Also… why doesn't FortAwesome have a package for this? While it's fun to
DIY and collaborate (🍻), I'd hope they fork this and  create an official
package. ❤️

**Comment by shyaniv7** [comment]
I actually reached out to them asking about it and they said I could work on it for them BUT since they make money off of their pro version I don’t think that doing this for them (for free) would qualify as open source and I couldnt promise the time comitement, so I just kept going on my own.

**Comment by beausmith** [comment]
Gotcha. Thx for the info.

**Comment by beausmith** [comment]
@shyaniv7 - Did you see this [PR for FA5 (free + pro) in for `react-native-vector-icons`](https://github.com/oblador/react-native-vector-icons/pull/776)?

**Comment by shyaniv7** [comment]
I just did. I hope they merge it. Rn vector icons is a very useful package but it’s also large, my idea was to create a small utility for the pro users since FA did not have their own

**Comment by beausmith** [comment]
I agree, a smaller FontAwesome specific react-native package is ideal.

**Comment by oblador** [comment]
@shyaniv7 It's actually not that large by default, you won't get any other fonts in your bundle unless you want to.

**Pull request merged**
